### PR TITLE
Fix #23: throw ScopeClosing if trying to fork in a closed scope

### LINKED ISSUE #23: Reconsider the behavior of trying to fork a new thread in a closing scope
Some background: conceptually, there are three states a scope can be in:

- "open", allowing new threads to be created within it
- "closing", because we reached the end of a `scoped` block naturally, or because we got hit by an exception, and are going to proceed to killing all living children and waiting for them to terminate
- "closed", because we're outside the callback in which the scope was valid, like any regular resource acquired in bracket-style

Clearly, we do want to disallow this bogus program, either with the type system (meh) or via a runtime exception:

```haskell
scope <- Ki.scoped pure
Ki.fork scope whatever -- using a scope outside its callback
```

On to the implementation. Each scope keeps an int count of the threads that are about to start, with the sentinel value -1 meaning closed/closing. When we go to fork a thread, if this counter is not -1, we bump the counter, then spawn the thread, then decrement the counter. If the counter _is_ -1, we throw a runtime exception (error "ki: scope closed").

This design makes closing a scope pretty simple: wait until there are 0 children about to start, then prevent new children from starting by writing -1, then kill all of the living children.

The problem (potentially) is that there's not actually a "closing" state that's distinguishable from "closed". So while we do prevent bogus programs like the above from spawning a thread in a _closed_ scope, it seems wrong to punish code that attempts to spawn a thread into a _closing_ scope in the same way.

Some options:

1. (straw man) Make `fork` have type `fork :: Scope -> IO a -> IO (Maybe (Thread a))`, and return Nothing if we try to fork a thread in a closing scope. I don't think this API is good, but it's conceptually what we are after. The current behavior (to reiterate/summarize the above) is to throw a lazy runtime exception with `error "ki: scope closing"` rather than return Nothing.
2. Make `Thread` a two-variant sum type, with a `DidntActuallyMakeTheThreadBecauseTheScopeWasClosing` variant. We'll have to decide what to do if you `await` such a thing.
3. Tweak the teardown dance to actually continue to allow threads to be created in a closing scope, if only to throw a `ScopeClosing` exception to them soon after (which is how we kill children). This doesn't seem meaningfully different to (2).
4. Something else, or nothing?

### PR DESCRIPTION
**Pull request by mitchellwrosen**
Fixes #23

### CODE REVIEW

File: ki/src/Ki/Internal/Scope.hs [hunk 1]
```diff
@@ -90,7 +91,8 @@ data Scope = Scope
     -- can continue to delay; there's no opportunity for an async exception to strike and prevent one of these threads
     -- from starting.
     --
-    -- Sentinel value: -1 means the scope is closed.
+    -- Sentinel value: -1 means the scope is closing.
+    -- Sentinel value: -2 means the scope is closed.
```
Comment (ocharles) [inline ki/src/Ki/Internal/Scope.hs:95]: Why do you use sentinel values instead of a proper sum type?

File: ki/src/Ki/Internal/Scope.hs [hunk 2]
```diff
@@ -210,9 +216,11 @@ spawn
...
       atomically do
         n <- readTVar startingVar
-        if n < 0
-          then throwSTM (ErrorCall "ki: scope closed")
-          else writeTVar startingVar $! n + 1
+        assert (n >= -2) do
+          if
+              | n >= 0 -> writeTVar startingVar $! n + 1
+              | n == -1 -> throwSTM ScopeClosing
+              | otherwise -> throwSTM (ErrorCall "ki: scope closed")
```
Comment (ocharles) [inline ki/src/Ki/Internal/Scope.hs:223]: If you had a sum type this would be a much cleaner `case` imo.

File: ki/src/Ki/Internal/Scope.hs (hunk 1 above)
Comment (ocharles) [reply ki/src/Ki/Internal/Scope.hs:95]: Hm, I think it'd be good to verify that! One sentinel value is liveable, but two starts getting very hairy! But then again, it's not my library :laughing:

Comment (mitchellwrosen) [reply ki/src/Ki/Internal/Scope.hs:95]: Hehe, good point. Well, I'd like to think of it not as "my" library either! I'll add benching that to the todo list.

Comment (TristanCacqueray) [reply ki/src/Ki/Internal/Scope.hs:95]: It would be interesting to know what is the overhead of using a sum type here. Out of curiosity I wrote this playground https://play.haskell.org/saved/r85araK7 , and it looks like doing `n >= 0` produces more core than a pattern match. Though I can't tell if that's better or not :)

**Comment by mitchellwrosen** [comment]
Ok, @tstat and I looked into the cmm and asm a bit here. We discovered that listing the `Open` data constructor _last_ resulted in the most efficient assembly (requiring one branch for the happy path, not two), with the following data type:

```haskell
data ScopeStatus
  = Closing
  | Closed
  | Open {-# UNPACK #-} !Int
```

(It's kind of lame that GHC doesn't take the user's match order into account). All else seemed equal, as far as just the price of pattern matching and reassembling one of these things goes.

However, the sum type is less desirable when closing a scope because, while waiting for the number of starting threads to drop to 0, know that the constructor is `Open`, yet still need to pay for the pattern match (and additionally once per unlikely `retry`).

So, I think a fair compromise is to just introduce a pattern synonym for readability. It's not as safe as a proper sum type of course. If anyone wants to put together an benchmark that actually measures the (probably negligible) performance hit of a few extra comparison instructions here and there, please go ahead. Because the little integer state machine isn't _that_ hard to grok (0+ to -1 to -2), and looks decently comprehensible with the pattern synonyms, I'm declaring this good enough for now.

File: ki/src/Ki/Internal/Scope.hs [hunk 3]
```diff
@@ -242,8 +264,8 @@ spawn
 
       -- Record the child as having started. Not allowed to retry.
       atomically do
-        n <- readTVar startingVar
-        writeTVar startingVar $! n - 1 -- it's actually ok to go from e.g. -1 to -2 here (very unlikely)
```
Comment (mitchellwrosen) [inline ki/src/Ki/Internal/Scope.hs:246]: This comment was inaccurate; we know `n` is 1 or more here.
